DECKS:
    -   name : draw deck
        contents : 1h 2h 3h 4h 5h 6h 7h 8h 9h 10h 11h 12h 13h 1s 2s 3s 4s 5s 6s 7s 8s 9s 10s 11s 12s 13s 1d 2d 3d 4d 5d 6d 7d 8d 9d 10d 11d 12d 13d 1c 2c 3c 4c 5c 6c 7c 8c 9c 10c 11c 12c 13c
        shuffle : yes
        hidden: yes
    -   name : face deck
        contents :
        shuffle : no
        hidden : no
    -   name : discard deck
        contents:
        shuffle: no
        hidden : no
PLAYERS:
    - player1
    - player2
    - player3
    - player4
PLAYER ATTRIBUTES:
    score : 0
    points : 0
    hand :
GAME ATTRIBUTES:
    highScore: 0
    counter : 0
    highPoint: 0
    best player: player1
    current player : player1
    starting player: player1
RULES:
    -   when starting
        so new game is started

    -   when new game is started
        if highScore isnt 1
        then announce "1"
        then for every player transfer 13 cards from draw deck into hand of player
        so new round is started

    -   when new game is started
        if highScore is 1
        then announce "2"
        so game is finished

    -   when new round is started
        if for any player hand of player is empty
        then announce "3"
        then increment score of best player
        so new game is started
    
    -   when new round is started
        if for any player hand of player is not empty
        then counter is now 0
        then highPoint is now 0
        then transfer size of face deck cards from face deck into discard deck 
        then announce "4"
        so new turn is started

    -   when new turn is started
        if counter is 4 
        then announce "5"
        then counter is now 0
        then increment point of best player
        then current player is now best player
        so new round is started
        
    -   when new turn is started
        then announce "6"
        unless counter is 4
        then annoucnes "1"
        then current player
            plays
                from hand of current player
                into face deck
                where
                    face deck is empty
                or
                    suit of choice is suit of top card of face deck
                or 
                    suit of choice is spade

        then best player is now
            current player
            where 
                        face deck has no card of suit spades
                    and 
                        rank of choice is highest rank in face deck
                or 
                        face deck has card of suit spades
                    and
                        suit of choice is spades
                    and 
                        rank of choice is highest rank in face deck of suit spades

        then rotate current player
        then increment counter
        so new turn is started
 